apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: default
  labels:
    app: cartservice
spec:
  type: ClusterIP
  ports:
  - name: grpc
    port: 7070
    targetPort: 7070
  selector:
    app: cartservice
