apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: default
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      serviceAccountName: currencyservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: ghcr.io/simzacks/refresher/currencyservice:latest
        ports:
          - containerPort: 7000
        env:
          - name: PORT
            value: "7000"
          - name: DISABLE_PROFILER # needed because pprof isn't working in the container
            value: "1"
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
        readinessProbe:
          initialDelaySeconds: 5
          grpc:
            port: 7000
        livenessProbe:
          initialDelaySeconds: 5
          grpc:
            port: 7000