apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  namespace: default
  labels:
    app: currencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currencyservice
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
        - name: server
          image: ghcr.io/simzacks/refresher/currencyservice:latest
          ports:
            - containerPort: 7000
          env:
            - name: PORT
              value: "7000"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            grpc:
              port: 7000
          livenessProbe:
            grpc:
              port: 7000