apiVersion: v1
kind: ServiceAccount
metadata:
  name: shippingservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  namespace: default
  labels:
    app: shippingservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shippingservice
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      serviceAccountName: shippingservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: ghcr.io/simzacks/refresher/shippingservice:latest
        ports:
          - containerPort: 50051
        env:
          - name: PORT
            value: "50051"
        resources:
          requests:
            cpu: 100m
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        readinessProbe:
          initialDelaySeconds: 5
          grpc:
            port: 50051
        livenessProbe:
          initialDelaySeconds: 5
          grpc:
            port: 50051
          
