apiVersion: v1
kind: ServiceAccount
metadata:
  name: recommendationservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: default
  labels:
    app: recommendationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      serviceAccountName: recommendationservice
      terminationGracePeriodSeconds: 5
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: ghcr.io/simzacks/refresher/recommendationservice:latest
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: PRODUCT_CATALOG_SERVICE_ADDR
            value: "productcatalogservice:3550"
        resources:
          requests:
            cpu: 100m
            memory: "64Mi"
          limits:
            cpu: "200m"
            memory: "128Mi"
        readinessProbe:
          initialDelaySeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          initialDelaySeconds: 5
          grpc:
            port: 8080
          
