apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  namespace: default
  labels:
    app: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymentservice
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
        - name: server
          image: ghcr.io/simzacks/refresher/paymentservice:latest
          ports:
            - containerPort: 50051
          env:
            - name: PORT
              value: "50051"
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            grpc:
              port: 50051
          livenessProbe:
            grpc:
              port: 50051